### ISSUE TITLE
json file setup

### ISSUE THREAD

**Issue by xxAOxx** [2m/zbap#2]
Love the project, I am close to having everything in place. Can you share the contents of a working json file? The one posted is empty.

**Comment by 2m** [comment]
I assume you are referring to `tags.json` file, right?

To create this file manually, you will need to get IDs of your NFC tags, which is a bit cumbersome. I recommend starting `zbap` and then navigating to `http://<raspberry_pi_ip>:8080/` where you will be able to associate tags with music files, which in turn will populate `tags.json` file.

**Comment by xxAOxx** [comment]
Ahh, very good.  Thank you for the quick reply.
